/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                "inverse-on-surface": "#eef2ed",
                "surface": "#f7faf6",
                "surface-container-low": "#f1f4f0",
                "secondary-fixed-dim": "#bec6e0",
                "surface-container": "#ecefeb",
                "on-error-container": "#93000a",
                "on-tertiary-fixed-variant": "#73332f",
                "secondary-container": "#dae2fd",
                "error": "#ba1a1a",
                "surface-muted": "#f8fafc",
                "surface-dim": "#d8dbd7",
                "on-primary-fixed": "#002116",
                "surface-bright": "#f7faf6",
                "on-primary-fixed-variant": "#00513b",
                "inverse-primary": "#8bd6b6",
                "on-error": "#ffffff",
                "tertiary-fixed": "#ffdad6",
                "tertiary": "#652925",
                "inverse-surface": "#2d312f",
                "on-tertiary-fixed": "#3b0908",
                "on-secondary-container": "#5c647a",
                "primary-container": "#065f46",
                "status-active": "#10b981",
                "on-secondary-fixed": "#131b2e",
                "on-tertiary-container": "#ffb4ad",
                "status-inactive": "#94a3b8",
                "secondary": "#565e74",
                "on-surface": "#181c1a",
                "surface-container-lowest": "#ffffff",
                "surface-tint": "#1b6b51",
                "outline-variant": "#bec9c2",
                "secondary-fixed": "#dae2fd",
                "surface-variant": "#e0e3df",
                "border-subtle": "#e2e8f0",
                "surface-container-high": "#e6e9e5",
                "on-surface-variant": "#3f4944",
                "tertiary-container": "#823f3a",
                "on-primary": "#ffffff",
                "tertiary-fixed-dim": "#ffb3ac",
                "status-error": "#ef4444",
                "on-secondary": "#ffffff",
                "on-primary-container": "#8bd6b7",
                "on-tertiary": "#ffffff",
                "error-container": "#ffdad6",
                "status-pending": "#f59e0b",
                "outline": "#6f7973",
                "background": "#f7faf6",
                "primary-fixed": "#a6f2d1",
                "surface-container-highest": "#e0e3df",
                "on-background": "#181c1a",
                "primary": "#004532",
                "on-secondary-fixed-variant": "#3f465c",
                "primary-fixed-dim": "#8bd6b6"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "touch-target": "44px",
                "container-margin-desktop": "40px",
                "container-margin-mobile": "16px",
                "base": "8px",
                "gutter": "24px"
            },
            fontFamily: {
                "display-lg": ["Plus Jakarta Sans"],
                "body-md": ["Inter"],
                "headline-lg": ["Plus Jakarta Sans"],
                "headline-md": ["Plus Jakarta Sans"],
                "headline-sm": ["Plus Jakarta Sans"],
                "label-md": ["Inter"],
                "headline-lg-mobile": ["Plus Jakarta Sans"],
                "body-lg": ["Inter"],
                "label-sm": ["Inter"],
                "body-sm": ["Inter"]
            },
            fontSize: {
                "display-lg": ["48px", {"lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
                "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
            }
        }
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
}
